name: semester_project_group_a

channels:
  - conda-forge
  - defaults
  dependencies:
    - scikit-learn == 1.4.2
    - pandas == 2.1.4
    - streamlit == 1.40.2
    - plotly == 5.24.1
    - shap == 0.46.0
    - matplotlib == 3.7.5